### ISSUE TITLE
Unhandled exception when starting app

### ISSUE THREAD

**Issue by hamperfait** [CervantesSec/cervantes#27]
I am running RHEL and I just installed the app. I had to disable IPv6 because I was getting an error, but once I got it running, I constantly get the same error on the console:
```
cervantes-app    | Unhandled exception. System.ArgumentNullException: Value cannot be null. (Parameter 'implementationInstance')
cervantes-app    |    at Microsoft.Extensions.DependencyInjection.ServiceCollectionServiceExtensions.AddSingleton[TService](IServiceCollection services, TService implementationInstance)
cervantes-app    |    at Cervantes.Web.Startup.ConfigureServices(IServiceCollection services) in /src/Cervantes.Web/Startup.cs:line 93
cervantes-app    |    at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
cervantes-app    |    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
cervantes-app    |    at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.InvokeCore(Object instance, IServiceCollection services)
cervantes-app    |    at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass9_0.<Invoke>g__Startup|0(IServiceCollection serviceCollection)
cervantes-app    |    at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.Invoke(Object instance, IServiceCollection services)
cervantes-app    |    at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass8_0.<Build>b__0(IServiceCollection services)
cervantes-app    |    at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.UseStartup(Type startupType, HostBuilderContext context, IServiceCollection services, Object instance)
cervantes-app    |    at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass13_0.<UseStartup>b__0(HostBuilderContext context, IServiceCollection services)
cervantes-app    |    at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
cervantes-app    |    at Microsoft.Extensions.Hosting.HostBuilder.Build()
cervantes-app    |    at Cervantes.Web.Program.Main(String[] args) in /src/Cervantes.Web/Program.cs:line 26
cervantes-app exited with code 139
cervantes-db     | 2022-10-10 09:35:15.221 UTC [61] FATAL:  database "cervantes" does not exist
cervantes-db     | 2022-10-10 09:35:15.351 UTC [62] FATAL:  database "cervantes" does not exist
cervantes-app    | Unhandled exception. System.ArgumentNullException: Value cannot be null. (Parameter 'implementationInstance')
cervantes-app    |    at Microsoft.Extensions.DependencyInjection.ServiceCollectionServiceExtensions.AddSingleton[TService](IServiceCollection services, TService implementationInstance)
cervantes-app    |    at Cervantes.Web.Startup.ConfigureServices(IServiceCollection services) in /src/Cervantes.Web/Startup.cs:line 93
cervantes-app    |    at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
cervantes-app    |    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
cervantes-app    |    at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.InvokeCore(Object instance, IServiceCollection services)
cervantes-app    |    at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass9_0.<Invoke>g__Startup|0(IServiceCollection serviceCollection)
cervantes-app    |    at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.Invoke(Object instance, IServiceCollection services)
cervantes-app    |    at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass8_0.<Build>b__0(IServiceCollection services)
cervantes-app    |    at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.UseStartup(Type startupType, HostBuilderContext context, IServiceCollection services, Object instance)
cervantes-app    |    at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass13_0.<UseStartup>b__0(HostBuilderContext context, IServiceCollection services)
cervantes-app    |    at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
cervantes-app    |    at Microsoft.Extensions.Hosting.HostBuilder.Build()
cervantes-app    |    at Cervantes.Web.Program.Main(String[] args) in /src/Cervantes.Web/Program.cs:line 26
cervantes-app exited with code 139
```
I haven't modified anything in the code except for the IPv6, but I doubt it would cause this many issues...

Any suggestions on how to proceed? Thanks!

**Comment by sysa20** [comment]
Hello is this issue still open, can I grab it?

**Comment by hamperfait** [comment]
Still fails for me, yes. I tried on my Parrot OS and still get the same errors. Haven't tried on a Windows environment though.

**Comment by mesquidar** [comment]
Hi @hamperfait , I made some changes on the docker repo and I rebuilt a new Cervantes image. Can you try again if its working well?

Thank you
Kind regards

**Comment by hamperfait** [comment]
It works now!
Thanks a lot for the quick response. Now I only have to see how to configure the ssl 😆
