### ISSUE TITLE
'How to run' instructions result in DbUpdateException (not-null constraint violation)

### ISSUE THREAD

**Issue by xAiluros** [CervantesSec/cervantes#63]
Just followed the instructions in readme, both docker compose and from source options result in the below exception.

Haven't had a chance yet to investigate / look at code.

```
Unhandled exception. Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while saving the entity changes. See the inner exception for details.
 ---> Npgsql.PostgresException (0x80004005): 23502: null value in column "ContentCss" of relation "ReportComponents" violates not-null constraint

DETAIL: Detail redacted as it may contain sensitive data. Specify 'Include Error Detail' in the connection string to include this information.
   at Npgsql.Internal.NpgsqlConnector.ReadMessageLong(Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(Boolean async, CommandBehavior behavior, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(Boolean async, CommandBehavior behavior, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior)
   at Npgsql.NpgsqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
  Exception data:
    Severity: ERROR
    SqlState: 23502
    MessageText: null value in column "ContentCss" of relation "ReportComponents" violates not-null constraint
    Detail: Detail redacted as it may contain sensitive data. Specify 'Include Error Detail' in the connection string to include this information.
    SchemaName: public
    TableName: ReportComponents
    ColumnName: ContentCss
    File: execMain.c
    Line: 2003
    Routine: ExecConstraints
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabase.SaveChanges(IList`1 entries)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IList`1 entriesToSave)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(StateManager stateManager, Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.<>c.<SaveChanges>b__112_0(DbContext _, ValueTuple`2 t)
   at Npgsql.EntityFrameworkCore.PostgreSQL.Storage.Internal.NpgsqlExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges()
   at Cervantes.DAL.DataInitializer.SeedTemplates(IReportTemplateManager reportTemplateManager, UserManager`1 userManager, IReportComponentsManager reportComponentsManager, IReportsPartsManager reportsPartsManager) in /home/debian/git/cervantes/Cervantes.DAL/DataInitializer.cs:line 182
   at Cervantes.DAL.DataInitializer.SeedData(UserManager`1 userManager, RoleManager`1 roleManager, IVulnCategoryManager vulnCategoryManager, IOrganizationManager organizationManager, IReportTemplateManager reportTemplateManager, ICweManager cweManager, String cwe, IReportComponentsManager reportComponentsManager, IReportsPartsManager reportsPartsManager) in /home/debian/git/cervantes/Cervantes.DAL/DataInitializer.cs:line 27
   at Program.<Main>$(String[] args) in /home/debian/git/cervantes/Cervantes.Web/Program.cs:line 279
```

**Comment by mesquidar** [comment]
Hi @xAiluros thanks for reporting the issue let me take it a look :)

**Comment by mesquidar** [comment]
Hi  @xAiluros 
I found the issue is related with the first seed of the database. I created a new image with the fix and it's already avalable if you want to try :)

Thank you

**Comment by xAiluros** [comment]
Hi @mesquidar 
Can confirm that it works now, thanks for the quick response & fix! :)
